package middleware

import (
	"bytes"
	"context"
	"encoding/json"
	"log"
	"net"
	"net/http"
	"time"
)

// RateCheckRequest matches the Pydantic V2 model expected by Phase 1
type RateCheckRequest struct {
	AccessKey *string `json:"access_key,omitempty"`
	IPKey     string  `json:"ip_key"`
	Limit     *int    `json:"limit,omitempty"`
	Window    *int    `json:"window,omitempty"`
}

// RateCheckSuccessResponse maps to the 200 OK structural output from Phase 1
type RateCheckSuccessResponse struct {
	Status       string `json:"status"` // E.g., "allowed"
	CurrentCount int    `json:"current_count"`
	Limit        int    `json:"limit"`
	Remaining    int    `json:"remaining"`
}

// FastAPIErrorResponse captures the native structural wrapper generated by HTTPException
type FastAPIErrorResponse struct {
	Detail json.RawMessage `json:"detail"`
}

// RateLimiterClient handles optimized outbound execution to the AWS Lambda service layer
type RateLimiterClient struct {
	httpClient *http.Client
	lambdaURL  string
}

// RateLimiterErrorDetail maps the internal 429 error structure from Phase 1
type RateLimiterErrorDetail struct {
	Message      string `json:"message" example:"Rate limit exceeded"`
	CurrentCount int    `json:"current_count" example:"11"`
	Limit        int    `json:"limit" example:"10"`
}

// RateCheck429Response maps the native FastAPI HTTPException structure for a 429 status
type RateCheck429Response struct {
	Detail RateLimiterErrorDetail `json:"detail"`
}

// RateCheck400Response maps the native FastAPI HTTPException structure for a 400 status
type RateCheck400Response struct {
	Detail string `json:"detail" example:"Token-authenticated requests must explicitly supply limit and window metrics."`
}

// NewRateLimiterClient instantiates a client configured with aggressive connection pooling
func NewRateLimiterClient(lambdaURL string, timeout time.Duration) *RateLimiterClient {
	return &RateLimiterClient{
		lambdaURL: lambdaURL,
		httpClient: &http.Client{
			Timeout: timeout,
			Transport: &http.Transport{
				Proxy: http.ProxyFromEnvironment,
				DialContext: (&net.Dialer{
					Timeout:   10 * time.Millisecond,
					KeepAlive: 30 * time.Second,
				}).DialContext,
				MaxIdleConns:          100,
				MaxIdleConnsPerHost:   100,
				IdleConnTimeout:       90 * time.Second,
				TLSHandshakeTimeout:   15 * time.Millisecond,
				ExpectContinueTimeout: 1 * time.Second,
			},
		},
	}
}

// IsAllowed executes the remote rate-check call, defaulting to true (FAIL-OPEN) on any unexpected failure
func (c *RateLimiterClient) IsAllowed(ctx context.Context, reqBody *RateCheckRequest) bool {
	payload, err := json.Marshal(reqBody)
	if err != nil {
		log.Printf("[RATE-LIMITER] Error marshaling request payload: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.lambdaURL, bytes.NewBuffer(payload))
	if err != nil {
		log.Printf("[RATE-LIMITER] Error creating HTTP request context: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		log.Printf("[RATE-LIMITER] Request failed or timed out: %v. Defaulting to FAIL-OPEN.", err)
		return true
	}
	defer resp.Body.Close()

	// Handle 200 OK Path
	if resp.StatusCode == http.StatusOK {
		var successResp RateCheckSuccessResponse
		if err := json.NewDecoder(resp.Body).Decode(&successResp); err != nil {
			log.Printf("[RATE-LIMITER] Error decoding 200 OK success payload: %v. Defaulting to FAIL-OPEN.", err)
			return true
		}
		return successResp.Status == "allowed"
	}

	// Handle Explicit 429 Too Many Requests Blocking Status
	if resp.StatusCode == http.StatusTooManyRequests {
		var errResp FastAPIErrorResponse
		if err := json.NewDecoder(resp.Body).Decode(&errResp); err == nil {
			log.Printf("[RATE-LIMITER] Blocked: 429 Rate Limit Exceeded. Detail Matrix: %s", string(errResp.Detail))
		} else {
			log.Printf("[RATE-LIMITER] Blocked: 429 Rate Limit Exceeded (Failed to parse detail metadata payload).")
		}
		return false
	}

	// Handle 400 Bad Request and all other non-200/429 states (Fail Open to safeguard experience)
	var errResp FastAPIErrorResponse
	if err := json.NewDecoder(resp.Body).Decode(&errResp); err == nil {
		log.Printf("[RATE-LIMITER] Alert: Upstream returned HTTP status %d. Detail: %s. Defaulting to FAIL-OPEN.", resp.StatusCode, string(errResp.Detail))
	} else {
		log.Printf("[RATE-LIMITER] Alert: Upstream returned HTTP status %d. Defaulting to FAIL-OPEN.", resp.StatusCode)
	}

	return true
}

// ResolveClientIP sanitizes and extracts the public edge IP passed explicitly by upstream gateways
func ResolveClientIP(r *http.Request) string {
	if xff := r.Header.Get("X-Forwarded-For"); xff != "" {
		parts := bytes.Split([]byte(xff), []byte(","))
		if len(parts) > 0 {
			return string(bytes.TrimSpace(parts[0]))
		}
	}
	if ip, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		return ip
	}
	return r.RemoteAddr
}

// RateLimitGuard creates the structural middleware layer interfacing with your engine control path
func RateLimitGuard(client *RateLimiterClient, executionTimeout time.Duration) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var accessKeyPtr *string
			if aud, ok := r.Context().Value(ContextAudienceKey).(string); ok && aud != "" {
				accessKeyPtr = &aud
			}

			ipKey := ResolveClientIP(r)

			reqPayload := &RateCheckRequest{
				AccessKey: accessKeyPtr,
				IPKey:     ipKey,
			}

			// Token-Based Strategy configuration tracking metrics
			if reqPayload.AccessKey != nil {
				limit := 1000
				window := 60
				reqPayload.Limit = &limit
				reqPayload.Window = &window
			}

			limiterCtx, cancel := context.WithTimeout(r.Context(), executionTimeout)
			defer cancel()

			if !client.IsAllowed(limiterCtx, reqPayload) {
				http.Error(w, "Too Many Requests: Rate limit exceeded or quota exhausted.", http.StatusTooManyRequests)
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}
