// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Evaluates a single state status targeting a specific composite namespace binding key.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Evaluation"
                ],
                "summary": "Get Individual Feature Flag Evaluation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target identifying domain service space",
                        "name": "service",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The distinct targeting feature gate identifier identifier",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Service [billing] Flag [enable-v2]: true",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing required parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized missing payload token signature",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests - Rate limit exceeded or quota exhausted",
                        "schema": {
                            "$ref": "#/definitions/middleware.RateCheck429Response"
                        }
                    }
                }
            }
        },
        "/get_flags": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Extracts the complete underlying operational state dataset block bounded to a single contextual microservice domain.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Evaluation"
                ],
                "summary": "Get All Component Configuration Flags for a Service Namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target identifying domain service space context parameter mapping string",
                        "name": "service",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Example output dictionary block payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests - Rate limit exceeded or quota exhausted",
                        "schema": {
                            "$ref": "#/definitions/middleware.RateCheck429Response"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifies running web engine operations and synchronous underlying upstash storage ping telemetry.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Engine Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests - Rate limit exceeded or quota exhausted",
                        "schema": {
                            "$ref": "#/definitions/middleware.RateCheck429Response"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable - Storage cluster connection broken",
                        "schema": {
                            "$ref": "#/definitions/main.HealthResponse"
                        }
                    }
                }
            }
        },
        "/set": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Commits an administrative state change parameter downward to secure cluster storage and instantly syncs internal tracking memory cache state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Administration"
                ],
                "summary": "Mutate/Set Target Feature State",
                "parameters": [
                    {
                        "description": "Target state runtime mutation specification matrix description block",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.FlagPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated flag [billing:enable-v2] to true",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid configuration format parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests - Rate limit exceeded or quota exhausted",
                        "schema": {
                            "$ref": "#/definitions/middleware.RateCheck429Response"
                        }
                    },
                    "500": {
                        "description": "Internal persistence storage communication error context",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Missing required parameters"
                }
            }
        },
        "main.FlagPayload": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "enable-stripe-v2"
                },
                "service": {
                    "type": "string",
                    "example": "billing-service"
                },
                "value": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "main.HealthResponse": {
            "type": "object",
            "properties": {
                "redis": {
                    "type": "string",
                    "example": "connected"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "middleware.RateCheck429Response": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/middleware.RateLimiterErrorDetail"
                }
            }
        },
        "middleware.RateLimiterErrorDetail": {
            "type": "object",
            "properties": {
                "current_count": {
                    "type": "integer",
                    "example": 11
                },
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "message": {
                    "type": "string",
                    "example": "Rate limit exceeded"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type 'Bearer \u003cyour_jwt_token\u003e' to access protected routes.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "headsntails Feature Engine API",
	Description:      "High-performance inline feature flagging control plane.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
